### ISSUE TITLE
Submit to arxiv

### ISSUE THREAD

**Issue by mdogucu** [jooyoungseo/teaching-accessibility-manuscript#11]
@jooyoungseo, I checked the JDS policy and it seems like they allow preprints. This weekend, after I submit to JDS, I can also submit to arxiv if that's fine with you too.

**Comment by jooyoungseo** [comment]
The repo is now public. I am not sure whether you would need this information in the preprint process, but I created arxiv id (with sighted assistance). My arxiv id is `jooyoungseo`.
